### ISSUE TITLE
There was an issue after core cluster and robot cluster setup

### ISSUE THREAD

**Issue by swgu931** [googlecloudrobotics/core#72]
I  did it below happily with the command "bash setup_robot.sh my-robot --project $PROJECT_ID --robot-type my-robot-type" 
I was OK I thought,.... but in the end I met the problem: I cannot drop the file to Cloud Storage.
please read my situation

```
:~/cloud-robotics-core$ bash setup_robot.sh my-robot --project $PROJECT_ID --robot-type my-robot-type
Generate access token with gcloud:
    gcloud auth application-default print-access-token
Enter access token:
<redacted>
gcr.io/cloud-robotics-releases/setup-robot@sha256:41dafd4447c6b3596d22ad6f1c0a5e5a09e03668dd37f7b045442355fb0c5e16
crc-0.1.0/crc-0.1.0+eb4de9b
No resources found
If you don't see a command prompt, try pressing enter.
2021/08/27 11:22:51 DNS lookup for "www.endpoints.cloud-robot-20200908.cloud.goog"
2021/08/27 11:22:51 Service probe for "https://www.endpoints.cloud-robot-20200908.cloud.goog/apis/core.token-vendor/v1/public-key.read"
2021/08/27 11:22:52 Creating new private key
2021/08/27 11:22:53 Publishing the robot's public key to Cloud IoT Registry
2021/08/27 11:22:53 Returning existing certificate.
2021/08/27 11:22:53 Initializing Synk
2021/08/27 11:22:54 Installing base-robot chart using Synk from base-robot-0.0.1.tgz
2021/08/27 11:23:02 Setup complete
pod "setup-robot" deleted
:~/cloud-robotics-core$ 
```

then I tried the section "Using Cloud Storage from a robot."
No problem with installing google-cloud-storage with my custom docker images which I used to test.
but the following command shows the error

```
root@python:~# python3
Python 3.8.4rc1 (default, Jul  1 2020, 15:31:45) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 's' from 'google.cloud' (unknown location)
>>> from google.cloud import storage
>>> client = storage.Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/client.py", line 124, in __init__
    super(Client, self).__init__(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/client.py", line 316, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/client.py", line 264, in __init__
    project = self._determine_default(project)
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/client.py", line 283, in _determine_default
    return _determine_default_project(project)
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/_helpers.py", line 152, in _determine_default_project
    _, project = google.auth.default()
  File "/usr/local/lib/python3.8/dist-packages/google/auth/_default.py", line 457, in default
    credentials, project_id = checker()
  File "/usr/local/lib/python3.8/dist-packages/google/auth/_default.py", line 219, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/usr/local/lib/python3.8/dist-packages/google/auth/_default.py", line 105, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File /shared/lg-cloud-robot-20200908-49bb09f5263f.json was not found.
```

So I was doubtful that it's ok for robot connect to cluster therefore I checked the below with kubectl command.
```
:~/cloud-robotics-core$ k get pod
NAME                                        READY   STATUS    RESTARTS   AGE
cr-syncer-569968cb56-gjc2n                  1/1     Running   7          2d3h
fluentd-gcp-v3.2.0-6v45k                    1/1     Running   7          2d3h
gcr-credential-refresher-6649954bb7-4z8dt   1/1     Running   3          2d3h
metadata-server-mcm6b                       1/1     Running   3          2d3h
robot-master-56fd8b597c-9dr5s               1/1     Running   6          2d3h


:~/cloud-robotics-core$ k get svc
NAME              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
cr-syncer         ClusterIP   10.105.147.107   <none>        80/TCP      2d3h
fluentd-metrics   ClusterIP   10.100.225.205   <none>        24231/TCP   2d3h
kubernetes        ClusterIP   10.96.0.1        <none>        443/TCP     2d3h
robot-master      ClusterIP   10.103.214.51    <none>        443/TCP     2d3h

:~/cloud-robotics-core$ k get endpoints
NAME              ENDPOINTS           AGE
cr-syncer         192.168.9.5:8080    2d3h
fluentd-metrics   192.168.9.3:24231   2d3h
kubernetes        192.168.9.1:6443    2d3h
robot-master      192.168.9.6:9876    2d3h

:~/cloud-robotics-core$ k get secret
NAME                  TYPE                                  DATA   AGE
default-token-gcww5   kubernetes.io/service-account-token   3      2d3h
gcr-json-key          kubernetes.io/dockercfg               1      2d3h
robot-auth            Opaque                                1      2d3h
robot-master-tls      kubernetes.io/tls                     2      2d3h

:~/cloud-robotics-core$ k get configmap
NAME                        DATA   AGE
fluentd-gcp-config-v1.2.5   4      2d3h
kube-root-ca.crt            1      2d3h
guber@guber-note:~/cloud-robotics-core$ 
```

please help me to solve it out
I am a robot engineer but I have been very interested in this platform which can help robot engineering.

Thanks a lot.
Sean

**Comment by swgu931** [comment]
Thanks Rodrigo Queiro.
it solved completely.

before that, google-cloud-storage installation was not finished even after 2 days passed, but it works after the command "apk add gcc musl-dev libffi-dev", which is brand-new information for me.

Thanks very much again.
Sean
